<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script> 
<div id="gitalk-container"></div>     <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
        clientID: '复制刚才生成的clientID',
        clientSecret: '复制刚才生成的clientSecret',
        repo: '自己博客的地址',
        owner: 'GitHub的用户名',
        admin: ['Github的用户名'],
        id:window.location.pathname,

    });
    gitalk.render('gitalk-container');
</script> 
<!-- Gitalk end -->
 ———————————————— 
版权声明：本文为CSDN博主「LSCR7」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/Madridcrls7/article/details/80871596
